project:
  type: website
  output-dir: _site

website:
  title: "Yakk-2 Blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts/
        text: Posts

format:
  html:
    theme: cosmo
    toc: true
    code-fold: false
    code-block-bg: true
    code-block-border-left: "#1f6feb"

execute:
  enabled: true

