project:
  type: website
  output-dir: _site

website:
  title: "Yakk-2 Blog"
  navbar:
    left:
      - href: using-quarto.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-fold: false
    code-block-bg: true
    code-block-border-left: "#1f6feb"

