project:
  type: website

website:
  title: "Yakk-2 Artificial Blog"
  navbar:
    left:
      - text: Home
        href: index.html
      - text: All Posts
        href: index.html
    right:
      - text: GitHub
        href: https://github.com/kedarmhaswade/yakk-2

execute:
  enabled: true
  echo: false
  warning: false
  freeze: false

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-fold: true
    code-block-bg: true
    code-block-border-left: "#1f6feb"
    navigation:
      toc: true
      prev-next: true

